<?php

/**
 * Aria S.p.A.
 * OPEN 2.0
 *
 *
 * @package    open20\amos\tag
 * @category   CategoryName
 */

namespace open20\amos\tag\assets;

use yii\web\AssetBundle;

/**
 * 
 */
class ModuleTagAsset extends AssetBundle
{
    /**
     * 
     * @var type
     */
    public $sourcePath = '@vendor/open20/amos-tag/src/assets/web';

    /**
     * 
     * @var type
     */
    public $css = [];

    /**
     * 
     * @var type
     */
    public $js = [
        'js/tag-js.js'
    ];

    /**
     * 
     * @var type
     */
    public $depends = [];

    /**
     * 
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}
